name: OvercastMimic
main: me.rainoboy97.scrimmage
version: 0.4
description: >
             A plugin to quickly enable team's to practice/scrimmage with others.
commands:
    start:
        description:
            Start the countdown for a match
    test:
        description:
            Test command, ignore.
    join:
        description:
            Join a team.
    g:
        description:
            Use global chat, everyone can hear you.
    cancel:
        description:
            Cancel the countdown for a match.
    tp:
        description:
            Teleport to a player in observers.
